language: node_js
node_js: “ls-remote”
install: nvm
script: nvm test
after_success:
 - nvm install -g codeclimate-test-reporter
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
 - codeclimate-test-reporter < lcov.info